= weercd
:author: Sébastien Helleu
:email: flashcode@flashtux.org
:lang: en

`weercd` is the WeeChat IRC testing server.

It can be used with any IRC client (not only WeeChat).

In the "flood" mode, various IRC commands are sent in a short time (privmsg,
notice, join/quit, ..) to test client resistance and memory usage (to quickly
detect memory leaks, for example with client scripts).

== Install

This script works with Python 2.x (>= 2.7) and 3.x.

It is *STRONGLY RECOMMENDED* to connect this server with a client in a test
environment:

* For WeeChat, another home with: `weechat --dir /tmp/weechat`.
* On a test machine, because CPU will be used a lot by client to display
  messages from weercd.
* If possible locally (ie server and client on same machine), to speed up
  data exchange between server and client.

== Run with WeeChat

Open a terminal and run server:

----
python weercd.py
----

Open another terminal and run WeeChat with home in '/tmp/weechat':

----
weechat --dir /tmp/weechat
----

Optional: install script(s) in WeeChat (for example `/script install xxx`).

Add server and connect to it:

----
/server add weercd 127.0.0.1/7777
/connect weercd
----

Wait some months...

WeeChat still not crashed and does not use 200 TB of RAM ? +
Yeah, it's stable! \o/

== Copyright

Copyright (C) 2011-2014 Sébastien Helleu <flashcode@flashtux.org>

This file is part of weercd, the WeeChat IRC testing server.

weercd is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

weercd is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with weercd.  If not, see <http://www.gnu.org/licenses/>.
